# Generated by Django 3.2 on 2021-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='tagged', to='tag.Tag'),
        ),
    ]
